export let AuthorizationAPI = "http://localhost:8080/AuthorizationAPI"
export let RegistrasiAPI = "http://localhost:8080/RegistrasiAPI"
export let LoginAPI = "http://localhost:8080/LoginAPI"

export let TambahFormAPI = "http://localhost:8080/TambahFormAPI"
export let AmbilSemuaFormAPI = "http://localhost:8080/AmbilSemuaFormAPI"
export let AmbilSatuFormDosenAPI = "http://localhost:8080/AmbilSatuFormDosenAPI"
export let AmbilSatuFormAdminAPI = "http://localhost:8080/AmbilSatuFormAdminAPI"
export let UpdateFormAPI = "http://localhost:8080/UpdateFormAPI"
export let HapusFormAPI = "http://localhost:8080/HapusFormAPI"